export enum Capitalizacion{
    ANUAL = 'ANUAL',
    SEMESTRAL = 'SEMESTRAL',
    CUATRIMESTRAL = 'CUATRIMESTRAL',
    TRIMESTRAL = 'TRIMESTRAL',
    BIMESTRAL = 'BIMESTRAL',
    MENSUAL = 'MENSUAL',
    QUINCENAL = 'QUINCENAL',
    SEMANAL = 'SEMANAL',
    DIARIA = 'DIARIA'
}