export enum Moneda {
    PEN = 'PEN',
    USD = 'USD',
    EUR = 'EUR',
    GBP = 'GBP',
    JPY = 'JPY',
    CNY = 'CNY',
    INR = 'INR',
    AUD = 'AUD',
    CAD = 'CAD',
    CHF = 'CHF',
    NZD = 'NZD',
    RUB = 'RUB',
    ZAR = 'ZAR',
    BRL = 'BRL',
    MXN = 'MXN',
    ARS = 'ARS',
    CLP = 'CLP',
    COP = 'COP',
    VEF = 'VEF',
    UYU = 'UYU',
}